[project]
name = "nfl-injury-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Cody Pak", email = "codyjhpak@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.43.98",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[project.scripts]
nfl-injury-tracker = "nfl_injury_tracker:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
